export const GET_POST = 'POST/CREATE_POST'
export const SHOP_FETCH_POSTS = 'SHOP/FETCH_POSTS'
export const SHOP_CHANGE_CARD = 'SHOP/CHANGE_CARD'

export const MD_POSTS_FETCH = 'MAIN/FETCH_POSTS'
export const SIDE_POSTS_FETCH = 'MAIN/SIDE_POSTS_FETCH'
export const SIDE_BAR_FETCH = 'MAIN/SIDE_BAR_FETCH'

export const DEFAULT = 'SHOP/DEFAULT'
